### ISSUE TITLE
500 Internal Server Error / Javascript popup, repeatedly

### ISSUE THREAD

**Issue by habernal** [TracksApp/tracks#2581]
Version: Tracks 2.5.1

Every 5 minutes or so, a Javascript popup is shown with ISE500.

Here's the (retracted) output from the Javascript console:

```
https://sever:port/login/check_expiry?_source_view=XXX&_group_view_by=YYY&_tag_name=&authenticity_token="ZZZ"&_=NNNNNN
```

**Comment by ZeiP** [comment]
Which installation method are you using? If it's an 500 error, you should be able to find more information from the server's error log.

**Comment by habernal** [comment]
I digged up the log:

```
I, [2021-02...01]  INFO -- : [46...c] Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.2ms | Allocations: 863)
F, [2021-02...01] FATAL -- : [46...c]   
[46...c] TypeError (expected numeric):
[46...c]   
[46...c] app/controllers/login_controller.rb:46:in `check_expiry'
```

As for installation, I'm using exactly those (which I contributed): https://github.com/TracksApp/tracks/wiki/Installing-Tracks-2.3.0-on-Ubuntu-14.04-LTS-on-AWS-with-SSL-support and https://github.com/TracksApp/tracks/wiki/Upgrade-from-2.4.2-to-2.5.1-on-AWS-Ubuntu-18.04-LTS

**Comment by lyonzy** [comment]
I'm getting this too - docker (compose) based installation of 2.5.1 with a mariadb database. Exact same `check_expiry` method. Happy to provide more details as well if you need. 
Compose file (partial):
```
version: '3'

services:

  server:
    restart: always
    image: tracksapp/tracks:master
    environment:
      - DATABASE_TYPE=mysql2
      - DATABASE_ENCODING=utf8
      - DATABASE_NAME=tracks
      - DATABASE_HOST=server
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=tracks
      - DATABASE_PASSWORD=[redacted]
    volumes:
      - ./site.yml:/app/config/site.yml

```
